name: Action di Cavescu
on: 
  push:
jobs: 
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "ciao sono una stringa"
      - run: echo "ciao sono una stringa 2"
      - run: python --version
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cavescu
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.2' 
      - run: python --version
      - run: python train_direction.py